### PR TITLE
Minified exceptions renderered pages too

### PR DESCRIPTION
**Pull request by mardiros**
Currently the plugin does not minify registred errors pages (for 404 page for instance

### CODE REVIEW

**Comment by sayoun** [comment]
I only see changelog entries in this PR there is no code change ?

**Comment by mardiros** [comment]
No I have commit the code in master, f*ck

**Comment by mardiros** [comment]
I have hardly reset master, sorry for that

**Comment by cr0cK** [comment]
:+1:

**Comment by pascalduez** [comment]
:+1:

**Comment by yanndinendal** [comment]
:+1:

**Pull request merged**
